apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "signalfx-agent.fullname" . }}
  namespace: {{ template "signalfx-agent.namespace" . }}
  labels:
    app: {{ template "signalfx-agent.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "signalfx-agent.chart" . }}
data:
  agent.yaml: |
{{- if .Values.agentConfig }}
{{ toYaml .Values.agentConfig | indent 4 }}
{{- else }}
    signalFxAccessToken: ${SFX_ACCESS_TOKEN}

    signalFxRealm: {{ .Values.signalFxRealm  | default "us0" }}

    {{- if .Values.ingestUrl }}
    ingestUrl: {{ .Values.ingestUrl }}
    {{- end }}

    {{- if .Values.apiUrl }}
    apiUrl: {{ .Values.apiUrl }}
    {{- end }}

    {{- if .Values.traceEndpointUrl }}
    traceEndpointUrl: {{ .Values.traceEndpointUrl }}
    {{- end }}

    etcPath: {{ .Values.etcPath }}
    procPath: {{ .Values.procPath }}

    intervalSeconds: {{ .Values.metricIntervalSeconds }}

    cluster: {{ required ".Values.clusterName is required" .Values.clusterName }}

    logging:
      level: {{ .Values.logLevel | default "info" }}

    globalDimensions:
      kubernetes_cluster: {{ .Values.kubernetesClusterName | default .Values.clusterName }}
      {{- range $k, $v := .Values.globalDimensions }}
      {{ $k }}: {{ $v }}
      {{- end }}

    sendMachineID: false

    observers:
    - type: k8s-api
      {{- if .Values.apiServerSkipVerify }}
      kubernetesAPI:
        skipVerify: true
      {{- end }}

    monitors:
    - type: collectd/cpu
    - type: collectd/cpufreq
    - type: collectd/df
      hostFSPath: {{ .Values.hostFSPath }}
    - type: collectd/disk
    - type: collectd/interface
    - type: collectd/load
    - type: collectd/memory
    - type: collectd/protocols
    - type: collectd/signalfx-metadata
      omitProcessInfo: true
    - type: host-metadata
    - type: processlist
    - type: collectd/uptime
    - type: collectd/vmem

    - type: kubelet-stats
      {{- if .Values.containerStatsIntervalSeconds }}
      intervalSeconds: {{ .Values.containerStatsIntervalSeconds }}
      {{- end }}
      {{- if .Values.kubeletAPI }}
      kubeletAPI:
        {{ toYaml .Values.kubeletAPI | indent 8 | trim }}
      {{- end }}
      datapointsToExclude:
      - dimensions:
          container_image:
           - '*pause-amd64*'
           - 'k8s.gcr.io/pause*'
        metricNames:
          - '*'
          - '!*network*'

    {{ if .Values.gatherClusterMetrics -}}
    # Collects k8s cluster-level metrics
    - type: {{.Values.kubernetesDistro}}-cluster
      useNodeName: true
    {{- end }}

    {{ if .Values.gatherDockerMetrics -}}
    - type: docker-container-stats
      dockerURL: unix:///var/run/docker.sock
      excludedImages:
       - '*pause-amd64*'
       - 'k8s.gcr.io/pause*'
      labelsToDimensions:
        io.kubernetes.container.name: container_spec_name
        io.kubernetes.pod.name: kubernetes_pod_name
        io.kubernetes.pod.uid: kubernetes_pod_uid
        io.kubernetes.pod.namespace: kubernetes_namespace
    {{- end }}

    {{ range .Values.monitors -}}
    - type: {{ .type }}
      {{- with .discoveryRule }}
      discoveryRule: {{ . }}
      {{- end }}
      {{- if (omit . "type" "discoveryRule") }}
      {{ toYaml (omit . "type" "discoveryRule") | indent 6 | trim }}
      {{- end }}

    {{ end }}

    collectd:
      readThreads: {{ .Values.readThreads | default 5 }}
      writeQueueLimitHigh: {{ .Values.writeQueueLimitHigh | default 500000 }}
      writeQueueLimitLow: {{ .Values.writeQueueLimitLow | default 400000 }}
      timeout: {{ .Values.timeout | default 40 }}
      logLevel: {{ .Values.logLevel | default "notice" }}

    enableBuiltInFiltering: true

    metricsToExclude:
      # The StackDriver metadata-agent pod on GKE restarts every few minutes so
      # ignore its containers
      - dimensions:
          container_spec_name: metadata-agent
      {{- if .Values.metricNamesToExclude }}
      - metricNames:
       {{- range .Values.metricNamesToExclude }}
        - "{{ . }}"
       {{- end }}
      {{- end }}
      {{- with .Values.metricsToExclude }}
{{ toYaml . | indent 6 }}
      {{- end }}
{{- end }}
