{{- $agentSemver := semver (.Values.agentVersion | default "0.0.0") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configmap-name" . }}
  namespace: {{ template "signalfx-agent.namespace" . }}
  labels:
    app: {{ template "signalfx-agent.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "signalfx-agent.chart" . }}
data:
  agent.yaml: |
{{- if .Values.agentConfig }}
{{ toYaml .Values.agentConfig | indent 4 }}
{{- else }}

    {{- if or (.Values.signalFxAccessToken) (.Values.signalFxAccessTokenSecretName)}}
    signalFxAccessToken: ${SFX_ACCESS_TOKEN}
    {{- end }}

    signalFxRealm: {{ .Values.signalFxRealm  | default "us0" }}

    {{- if .Values.ingestUrl }}
    ingestUrl: {{ .Values.ingestUrl }}
    {{- end }}

    {{- if .Values.apiUrl }}
    apiUrl: {{ .Values.apiUrl }}
    {{- end }}

    {{- if .Values.traceEndpointUrl }}
    traceEndpointUrl: {{ .Values.traceEndpointUrl }}
    {{- end }}

    disableHostDimensions: {{ toYaml .Values.isServerless }}

    etcPath: {{ .Values.etcPath }}
    procPath: {{ .Values.procPath }}

    enableBuiltInFiltering: true

    intervalSeconds: {{ .Values.metricIntervalSeconds }}

    cluster: {{ required ".Values.clusterName is required" .Values.clusterName }}

    writer:
    {{- if semverCompare ">=5.3.0" $agentSemver.Original }}
      signalFxEnabled: {{ .Values.signalFxEnabled }}
    {{- end }}
    {{- if .Values.splunkUrl }}
      splunk:
        enabled: true
        url: {{ .Values.splunkUrl }}
        token: ${SPLUNK_TOKEN}
        {{- if .Values.splunkIndex }}
        index: {{ .Values.splunkIndex }}
        {{- end }}
        {{- if .Values.splunkSource }}
        source: {{ .Values.splunkSource }}
        {{- end }}
        {{- if .Values.splunkSourceType }}
        sourceType: {{ .Values.splunkSourceType }}
        {{- end }}
        skipTLSVerify: {{ .Values.splunkSkipTLSVerify | default "false" }}
    {{- end }}

{{- if lt $agentSemver.Major 5 }}
    sendMachineID: false
{{- end }}

    logging:
      level: {{ .Values.logLevel | default "info" }}
      format: {{ .Values.logFormat | default "text" }}

    globalDimensions:
      kubernetes_cluster: {{ .Values.kubernetesClusterName | default .Values.clusterName }}
      {{- range $k, $v := .Values.globalDimensions }}
      {{ $k }}: {{ $v }}
      {{- end }}

    observers:
    - type: k8s-api
      {{- if .Values.apiServerSkipVerify }}
      kubernetesAPI:
        skipVerify: true
      {{- end }}
      discoverAllPods: {{ toYaml .Values.isServerless }}
      discoverNodes: {{ toYaml .Values.isServerless }}
      {{- if .Values.additionalPortAnnotations }}
      additionalPortAnnotations:
      {{ range .Values.additionalPortAnnotations -}}
      - {{ toYaml . | indent 8 | trim }}
      {{- end }}
      {{- end }}

    monitors:
{{- if .Values.configureStandardMonitors }}
{{- if not .Values.isServerless }}
{{- if ge $agentSemver.Major 5 }}
    - type: cpu
    - type: filesystems
      hostFSPath: {{ .Values.hostFSPath }}
    - type: disk-io
    - type: net-io
    - type: load
    - type: memory
    - type: host-metadata
    - type: processlist
    - type: vmem
{{- else }}
    - type: collectd/cpu
    - type: collectd/cpufreq
    - type: collectd/df
      hostFSPath: /hostfs
    - type: disk-io
    - type: collectd/interface
    - type: load
    - type: collectd/memory
    - type: collectd/protocols
    - type: collectd/signalfx-metadata
      omitProcessInfo: true
    - type: host-metadata
    - type: processlist
    - type: collectd/uptime
    - type: collectd/vmem
{{- end }}
{{- end }}

{{ $hasKubeletMetrics := semverCompare ">=5.3.0" $agentSemver.Original }}
    - type: kubelet-{{if $hasKubeletMetrics}}metrics{{else}}stats{{end}}
      {{- if .Values.isServerless }}
      # Change 'fargate' part to something else if using another serverless K8s
      # platform.  We avoid scraping kubelet stats from the same node as the
      # agent because EKS restricts connections between a pod and its own
      # virtual kubelet, but not other kubelets.
      discoveryRule: 'target == "k8s-node" && name =~ "fargate" && name != Getenv("MY_NODE_NAME")'
      configEndpointMappings:
        kubeletAPI: |
          {
            url: Sprintf("https://%s:%d", host, node_status.DaemonEndpoints.KubeletEndpoint.Port),
            authType: "serviceAccount"
          }
      {{- end }}
      {{- if .Values.containerStatsIntervalSeconds }}
      intervalSeconds: {{ .Values.containerStatsIntervalSeconds }}
      {{- end }}
      {{- if .Values.kubeletAPI }}
      kubeletAPI:
        {{ toYaml .Values.kubeletAPI | indent 8 | trim }}
      {{- end }}
      {{- if $hasKubeletMetrics }}
      usePodsEndpoint: {{ .Values.usePodsEndpoint }}
      {{- else }}
      datapointsToExclude:
      - dimensions:
          container_image:
           - '*pause-amd64*'
           - 'k8s.gcr.io/pause*'
        metricNames:
          - '*'
          - '!*network*'
      {{- end }}

    {{ if .Values.gatherClusterMetrics -}}
    # Collects k8s cluster-level metrics
    - type: {{.Values.kubernetesDistro}}-cluster
{{- if lt $agentSemver.Major 5 }}
      useNodeName: true
{{- end }}
{{- if .Values.isServerless }}
      alwaysClusterReporter: true
{{- end }}
    {{- end }}

    {{ if not .Values.isServerless -}}
    {{ if .Values.gatherDockerMetrics -}}
    - type: docker-container-stats
      dockerURL: unix:///var/run/docker.sock
      excludedImages:
       - '*pause-amd64*'
       - 'k8s.gcr.io/pause*'
      labelsToDimensions:
        io.kubernetes.container.name: container_spec_name
        io.kubernetes.pod.name: kubernetes_pod_name
        io.kubernetes.pod.uid: kubernetes_pod_uid
        io.kubernetes.pod.namespace: kubernetes_namespace
    {{- end }}
    {{- end }}
{{- end }}
    {{ range .Values.monitors -}}
    - type: {{ .type }}
      {{- with .discoveryRule }}
      discoveryRule: {{ . }}
      {{- end }}
      {{- if (omit . "type" "discoveryRule") }}
      {{ toYaml (omit . "type" "discoveryRule") | indent 6 | trim }}
      {{- end }}

    {{ end }}

    collectd:
      readThreads: {{ .Values.readThreads | default 5 }}
      writeQueueLimitHigh: {{ .Values.writeQueueLimitHigh | default 500000 }}
      writeQueueLimitLow: {{ .Values.writeQueueLimitLow | default 400000 }}
      timeout: {{ .Values.timeout | default 40 }}
      logLevel: {{ .Values.logLevel | default "notice" }}

    metricsToExclude:
      # The StackDriver metadata-agent pod on GKE restarts every few minutes so
      # ignore its containers
      - dimensions:
          container_spec_name: metadata-agent
      {{- if .Values.metricNamesToExclude }}
      - metricNames:
       {{- range .Values.metricNamesToExclude }}
        - "{{ . }}"
       {{- end }}
      {{- end }}
      {{- with .Values.metricsToExclude }}
{{ toYaml . | indent 6 }}
      {{- end }}
{{- end }}
