
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[constraint]]
  name = "github.com/Knetic/govaluate"
  version = "2.3.0"

[[constraint]]
  name = "github.com/ShowMax/go-fqdn"

[[constraint]]
  name = "github.com/creasty/defaults"
  revision = "70562fe606572ce5d1a2abb2039bcbdc18709c01"
  source = "github.com/signalfx/defaults"

[[constraint]]
  name = "github.com/davecgh/go-spew"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "6e5c2d639f67ae70f54d9f2285f3261440b074aa"

[[override]]
  name = "github.com/docker/distribution"
  revision = "fea8bd51143307d3454703eadecbeeb778aa75e8"

[[override]]
  name = "google.golang.org/cloud"
  revision = "15454a9f4f17e9fc086c36d48d595f8dbef13e24"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"

[[constraint]]
  name = "github.com/google/cadvisor"
  version = "0.26.1"

[[constraint]]
  name = "github.com/kr/pretty"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/onsi/gomega"

[[constraint]]
  name = "github.com/signalfx/com_signalfx_metrics_protobuf"

[[constraint]]
  name = "github.com/signalfx/golib"
  revision = "0bcb5ca7f1efc1ba4a2fbaadd3dfb3c1d32e8429"

[[constraint]]
  name = "github.com/signalfx/metricproxy"
  revision = "6d1b2d7f104e77f09d6df1fc62ce1c092d8ab3de"

[[constraint]]
  name = "github.com/sirupsen/logrus"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.1.4"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/fatih/set.v0"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.18.07"

# temporarily overriding until https://github.com/shirou/gopsutil/pull/549 is merged
[[override]]
  name = "github.com/shirou/gopsutil"
  source = "github.com/pytimer/gopsutil"
  revision = "0ffcfc901f82fc83dc98c51c25ea60c996a1c781"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/hashstructure"

[[constraint]]
  branch = "master"
  name = "github.com/samuel/go-zookeeper"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.0"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "180eddb345a5be3a157cea1c624700ad5bd27b8f"

[[override]]
  name = "golang.org/x/text"
  revision = "e19ae1496984b1c655b8044a65c0300a3c878dd3"

[[override]]
  name = "golang.org/x/exp"
  revision = "f2486d8f4791367d077f7fa69b7855041f5b2ddf"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.9.5"

[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "0.4.9"

[[constraint]]
  name = "github.com/signalfx/telegraf"
  version = "1.7.1.sfx0"

[[constraint]]
  name = "github.com/influxdata/telegraf"
  version = "1.7.1"

[[constraint]]
  name = "github.com/ulule/deepcopier"
  revision = "ca99b135e50f526fde9cd88705f0ff2f3f95b77c"
