
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "=1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "=2.4.0"
[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[constraint]]
  name = "github.com/Knetic/govaluate"
  version = "=2.3.0"

[[constraint]]
  name = "github.com/ShowMax/go-fqdn"

[[constraint]]
  name = "github.com/creasty/defaults"
  revision = "70562fe606572ce5d1a2abb2039bcbdc18709c01"
  source = "github.com/signalfx/defaults"

[[constraint]]
  name = "github.com/davecgh/go-spew"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "6e5c2d639f67ae70f54d9f2285f3261440b074aa"

[[override]]
  name = "github.com/docker/distribution"
  revision = "fea8bd51143307d3454703eadecbeeb778aa75e8"

[[override]]
  name = "google.golang.org/cloud"
  revision = "15454a9f4f17e9fc086c36d48d595f8dbef13e24"

[[override]]
  name = "github.com/gogo/protobuf"
  revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"
  
[[override]]
  name = "github.com/golang/protobuf"
  revision = "aa810b61a9c79d51363740d207bb46cf8e620ed5"

[[constraint]]
  name = "github.com/google/cadvisor"
  version = "=0.26.1"

[[constraint]]
  name = "github.com/kr/pretty"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "=1.3.1"

[[constraint]]
  name = "github.com/onsi/gomega"

[[constraint]]
  name = "github.com/signalfx/com_signalfx_metrics_protobuf"

[[constraint]]
  name = "github.com/signalfx/golib"
  revision = "951bd0ba96011685e7ebcc24bc02a9fab93333b5"

[[constraint]]
  name = "github.com/signalfx/gateway"
  revision = "8421d05558e88bce0d8342f2cdebad6e6b109c89"

[[constraint]]
  name = "github.com/sirupsen/logrus"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.2.2"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"

[[constraint]]
  name = "gopkg.in/fatih/set.v0"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "=2.18.12"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/hashstructure"

[[constraint]]
  branch = "master"
  name = "github.com/samuel/go-zookeeper"

[[constraint]]
  name = "github.com/coreos/etcd"
  revision = "27fc7e2296f506182f58ce846e48f36b34fe6842"

[[override]]
  name = "google.golang.org/grpc"
  revision = "41344da2231b913fa3d983840a57a6b1b7b631a1"

[[override]]
  name = "google.golang.org/genproto"
  revision = "11c7f9e547da6db876260ce49ea7536985904c9b"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "=0.2.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "=8.0.0"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "103fd098999dc9c0c88536f5c9ad2e5da39373ae"

[[override]]
  name = "golang.org/x/text"
  revision = "e19ae1496984b1c655b8044a65c0300a3c878dd3"

[[override]]
  name = "golang.org/x/exp"
  revision = "f2486d8f4791367d077f7fa69b7855041f5b2ddf"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=1.12.0"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "=0.4.9"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
  name = "github.com/signalfx/telegraf"
  revision = "888c034dc63b1420acc06188f1af72a5b19872e2"

[[override]]
  name = "github.com/coreos/bbolt"
  revision = "7ee3ded59d4835e10f3e7d0f7603c42aa5e83820"

[[override]]
  name = "github.com/quentin-m/etcd-cloud-operator"
  source = "github.com/signalfx/etcd-cloud-operator"
  revision = "b18fdd887d97ccf755e4737d14d8a9b9e97bbc9e"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "=1.0.2"

[[constraint]]
  name = "github.com/influxdata/telegraf"
  version = "=1.9.4"

[[constraint]]
  name = "github.com/ulule/deepcopier"
  revision = "ca99b135e50f526fde9cd88705f0ff2f3f95b77c"

[[constraint]]
  name = "github.com/kardianos/service"
  revision = "615a14ed75099c9eaac6949e22ac2341bf9d3197"

[[override]]
  name = "github.com/StackExchange/wmi"
  revision = "b12b22c5341f0c26d88c4d66176330500e84db68"

[[override]]
  name = "golang.org/x/sys"
  revision = "afcc84fd7533758f95a6e93ae710aa945a0b7e73"
