
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Knetic/govaluate"
  version = "2.3.0"

[[constraint]]
  name = "github.com/ShowMax/go-fqdn"

[[constraint]]
  name = "github.com/creasty/defaults"

[[constraint]]
  name = "github.com/davecgh/go-spew"

[[constraint]]
  name = "github.com/docker/engine-api"
  version = "0.4.0"

[[constraint]]
  name = "github.com/docker/libkv"
  source = "https://github.com/signalfx/libkv.git"

[[constraint]]
  name = "github.com/gogo/protobuf"

[[constraint]]
  name = "github.com/google/cadvisor"
  version = "0.26.1"

[[constraint]]
  name = "github.com/kr/pretty"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/onsi/gomega"

[[constraint]]
  name = "github.com/pebbe/zmq4"

[[constraint]]
  name = "github.com/signalfx/com_signalfx_metrics_protobuf"

[[constraint]]
  name = "github.com/signalfx/golib"

[[constraint]]
  name = "github.com/signalfx/metricproxy"
  version = "0.9.18"

[[constraint]]
  name = "github.com/sirupsen/logrus"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.1.4"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/fatih/set.v0"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "2.0.0"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.17.11"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/hashstructure"

[[constraint]]
  branch = "master"
  name = "github.com/samuel/go-zookeeper"
