---
galaxy_info:
  role_name: smart_agent
  author: SignalFx
  description: Ansible role to install and configure the SignalFx Smart Agent
  company: SignalFx, Inc.
  license: Apache-2.0
  min_ansible_version: 2.4.1
  platforms:
  - name: EL
    versions:
      - 8
      - 7
  - name: Ubuntu
    versions:
      - bionic
      - xenial
      - trusty
  - name: Debian
    versions:
      - stretch
      - jessie
  - name: Amazon
  - name: Windows
  galaxy_tags:
    - signalfx
    - metrics
    - agent
    - monitoring

dependencies: []
