apiVersion: v1
description: The SignalFx Smart Agent
name: signalfx-agent
appVersion: 5.3.0
version: 1.1.0
keywords:
- monitoring
- alerting
- metrics
- stats
home: https://signalfx.com
sources:
- https://github.com/signalfx/signalfx-agent
maintainers:
- name: keitwb
  email: benkeith@splunk.com
- name: jchengsfx
  email: jeffreyc@splunk.com
- name: jaysfx
  email: jcamp@splunk.com
- name: mstumpfx
  email: mstumpf@splunk.com
icon: https://signalfx-82c9.kxcdn.com/wp-content/uploads/2015/12/signalfx-main-logo1.png
