apiVersion: v1
description: The SignalFx Smart Agent
name: signalfx-agent
appVersion: 4.7.7
version: 0.4.1
keywords:
- monitoring
- alerting
- metrics
- stats
home: https://signalfx.com
sources:
- https://github.com/signalfx/signalfx-agent
maintainers:
- name: keitwb
  email: bkeith@signalfx.com
- name: charliesignalfx
  email: charlie@signalfx.com
- name: jchengsfx
  email: jcheng@signalfx.com
icon: https://signalfx-82c9.kxcdn.com/wp-content/uploads/2015/12/signalfx-main-logo1.png
