# *Required* The access token for the org that you wish to send metrics to.
signalFxAccessToken: ${SFX_ACCESS_TOKEN}
ingestUrl: ${SFX_INGEST_URL}
apiUrl: ${SFX_API_URL}

intervalSeconds: 10

etcPath: /hostfs/etc
procPath: /hostfs/proc
runPath: /hostfs/run
varPath: /hostfs/var
sysPath: /hostfs/sys

logging:
  # Valid values are 'debug', 'info', 'warning', and 'error'
  level: info

# observers are what discover running services in the environment
observers:
  - type: docker

monitors:
  - {"#from": "/etc/signalfx/monitors/*.yaml", flatten: true, optional: true}
  - type: collectd/cpu
  - type: collectd/cpufreq
  - type: collectd/df
    hostFSPath: /hostfs
  - type: collectd/disk
  - type: collectd/interface
  - type: collectd/load
  - type: collectd/memory
  - type: collectd/vmem
  - type: collectd/signalfx-metadata
    omitProcessInfo: true
  - type: host-metadata
  - type: processlist
  - type: docker-container-stats

enableBuiltInFiltering: true
