sfx_agent_config:
  signalFxAccessToken: MyToken
  enableBuiltInFiltering: true
  monitors:
    - type: collectd/cpu
    - type: collectd/cpufreq
    - type: collectd/df
    - type: collectd/disk
    - type: collectd/interface
    - type: collectd/load
    - type: collectd/memory
    - type: collectd/signalfx-metadata
      omitProcessInfo: true
    - type: host-metadata
    - type: processlist
    - type: collectd/vmem
