---
- name: Delete old signing key for SignalFx Agent
  rpm_key:
    key: 098acf3b
    state: absent

- name: Add Signalfx Agent repo into source list
  yum_repository:
    name: signalfx-agent
    description: SignalFx Agent Repository
    baseurl: "{{ sfx_repo_base_url }}/signalfx-agent-rpm/{{ sfx_package_stage }}"
    gpgkey: "{{ sfx_repo_base_url }}/signalfx-agent-rpm/splunk-B3CD4420.pub"
    gpgcheck: yes
    enabled: yes

- name: Install signalfx-agent via yum package manager
  yum: 
    name: signalfx-agent{% if sfx_version is defined and sfx_version != "latest" %}-{{ sfx_version }}{% endif %}
    state: "{% if sfx_version is defined and sfx_version != 'latest' %}present{% else %}{{ sfx_version }}{% endif %}"
    allow_downgrade: yes
    update_cache: yes
