monitors:
- dimensions: null
  doc: |
    Pulls container stats from the Docker Engine.  We
    strongly recommend using the
    [docker-container-stats](./docker-container-stats.md) monitor instead, as it
    will scale to large number of containers much better.

    See https://github.com/signalfx/docker-collectd-plugin.
  metrics: null
  monitorType: collectd/docker
  properties: null
