---
# Default values for for Signalfx Agent installation

sfx_repo_base_url: https://splunk.jfrog.io/splunk
sfx_package_stage: release
sfx_version: latest

sfx_conf_file_path: /etc/signalfx/agent.yaml

sfx_service_user: signalfx-agent
sfx_service_group: signalfx-agent

sfx_win_install_path: "C:\\Program Files\\SignalFx"
sfx_win_conf_file_path: "\\ProgramData\\SignalFxAgent\\agent.yaml"
sfx_win_dl_base_url: https://dl.signalfx.com
